# PUC Minas Virtual

## Métodos de Programação Aplicados ao Mercado Financeiro

Este é o décimo notebook da nossa disciplina, sobre cálculos matemáticos, incluindo cálculos com vetores e matrizes.

Autor: Prof. Leopoldo Grajeda

Data da última atualização: 06/02/2023

In [1]:
# A biblioteca MATH reúne as ferramentas elementares da Matemática.

import math

In [2]:
# Número de Euler

math.e

2.718281828459045

In [3]:
# Função exponecial

x = 3.0    # Escolha o valor de x para calcular a função exponencial

math.exp(x)

20.085536923187668

In [4]:
# Alternativamente a função exponecial poderia ser calculada usando potência de base e

x = 3.0    # Escolha o valor de x para calcular a função exponencial

math.e**x

20.085536923187664

In [5]:
# Função logaritmo natural

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde logaritmo sem base é sempre o logarimo natural.

x = 3.0    # Escolha o valor de x para calcular o logaritmo natural

math.log(x)

1.0986122886681098

In [6]:
# Função logaritmo na base 10

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde logaritmo sem base é sempre o logarimo natural.

x = 3.0    # Escolha o valor de x para calcular o logaritmo na base 10

math.log10(x)

0.47712125471966244

In [7]:
# Número Pi

math.pi

3.141592653589793

In [8]:
# Função seno

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde as funções trigonométricas usam sempre radianos.

x = 1.0    # Escolha o valor de x para calcular o seno

math.sin(x)

0.8414709848078965

In [9]:
# Função cosseno

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde as funções trigonométricas usam sempre radianos.

x = 1.0    # Escolha o valor de x para calcular o cosseno

math.cos(x)

0.5403023058681398

In [10]:
# Função tangente

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde as funções trigonométricas usam sempre radianos.

x = 1.0    # Escolha o valor de x para calcular a tangente

math.tan(x)

1.5574077246549023

In [11]:
# Funções trigonométricas inversas

# Importante: o Python utiliza a convenção do Sistema Intenacional
#             onde as funções trigonométricas usam sempre radianos.

x = 1.0    # Escolha o valor de x para calcular as funções inversas

math.asin(x), math.acos(x), math.atan(x)

(1.5707963267948966, 0.0, 0.7853981633974483)

In [12]:
# A biblioteca NUMPY reúne mais ferramentas da Matemática, incluindo vetores e matrizes.

import numpy as np

In [13]:
# Vetores podem ser declarados usando o tipo ARRAY

v = np.array([1,2,3,4,5])   # Declaração do vetor v, com 5 coordenadas

v                           # Exibição do vetor v

array([1, 2, 3, 4, 5])

In [14]:
# Vetor nulo

z = np.zeros(5)             # Declaração do vetor nulo com 5 coordenadas

z                           # Exibição do vetor z

array([0., 0., 0., 0., 0.])

In [15]:
# Vetor de 1's

u = np.ones(5)             # Declaração do vetor de 1's com 5 coordenadas

u                           # Exibição do vetor u

array([1., 1., 1., 1., 1.])

In [16]:
# Soma de vetores

u + v

array([2., 3., 4., 5., 6.])

In [17]:
# Diferença de vetores

u - v

array([ 0., -1., -2., -3., -4.])

In [18]:
# Multiplicação de vetor por escalar

5*u

array([5., 5., 5., 5., 5.])

In [19]:
# Expressões algébricas com vetores

3*u - v

array([ 2.,  1.,  0., -1., -2.])

In [20]:
# Produto escalar de dois vetores

np.dot(u,v)

15.0

In [21]:
# A biblioteca NUMPY redefine todas as funções elementares, com uma implementação vetorial.
# Ao ser aplicadas a um vetor, as funções aplicam-se a cada coordenada do vetor.
# O resultado será um novo vetor, com o mesmo número de coordenadas.

np.exp(v)     # A função exponencial aplicada a cada coordenada de v

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [22]:
# Além de vetores, o tipo ARRAY do NUMPY pode também acomodar matrizes.
# As matrizes podem ser declaradas linha por linha.

N = np.array([[1,2],[1,0],[3,2],[-1,0],[3,-2]])  # Exemplo de matriz com 5 linhas e 2 colunas

N

array([[ 1,  2],
       [ 1,  0],
       [ 3,  2],
       [-1,  0],
       [ 3, -2]])

In [23]:
# Matriz nula

Z23 = np.zeros([2,3])   # Matriz nula 2x3

Z23

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Matriz identidade

I5 = np.identity(5)   # Matriz identidade 5x5

I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# Matriz de 1's

U45 = np.ones([4,5])   # Matriz de 1's 4x5

U45

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Soma de matrizes do mesmo formato

N + N

array([[ 2,  4],
       [ 2,  0],
       [ 6,  4],
       [-2,  0],
       [ 6, -4]])

In [27]:
# Multiplicação de matriz por escalar

5*N

array([[  5,  10],
       [  5,   0],
       [ 15,  10],
       [ -5,   0],
       [ 15, -10]])

In [28]:
# Multiplicação de matrizes de formato compatível

# Importante: a multiplicação de matrizes usa o símbolo de @, ao invés do *.

I5 @ N

array([[ 1.,  2.],
       [ 1.,  0.],
       [ 3.,  2.],
       [-1.,  0.],
       [ 3., -2.]])

In [29]:
# Potência de matrizes quadradas

(2*I5)**3

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [30]:
# O formato de uma matriz pode ser obtido pela propriedade SHAPE

N.shape

(5, 2)