# PUC Minas Virtual

## Métodos de Programação Aplicados ao Mercado Financeiro

Este é o 11º notebook da nossa disciplina, sobre equilíbrio de mercado.

Autor: Prof. Leopoldo Grajeda

Data da última atualização: 06/02/2023

In [1]:
# Carregamento da biblioteca NumPy.

import numpy as np

### Market share

Em uma cidade há 4 companhias de telefonia celular: A, B, C e D. O market share de cada companhia pode ser representado por um vetor de estado.

In [2]:
# Lista das companhias telefônicas
Operadoras = ['A', 'B', 'C', 'D']

# O vetor de participação de mercado inicial
p = [np.array([0.40, 0.25, 0.20, 0.15])]

# Exibição da participação de mercado
print('Participação de mercado (market share):')
for k in range(len(Operadoras)):
    print(f'- Operadora {Operadoras[k]}: {p[0][k]:,.2%}')

Participação de mercado (market share):
- Operadora A: 40.00%
- Operadora B: 25.00%
- Operadora C: 20.00%
- Operadora D: 15.00%


### Mudança de operadora

A cada ano muitos clientes que trocam de operadora, isso pode ser representado por uma matriz de transição, indicando o percentual de clientes que troca de operadora.

Aqui, cada entrada da matriz tem sua linha correspondente à nova operadora e sua coluna, à operadora de origem, enquanto que seu valor mostra o percentual de clientes que deixam a operadora de origem e mudam para a nova operadora a cada ano. (Note que a diagonal principal indica os clientes que permanecem na mesma operadora.)

In [3]:
# Definição da matriz de transição
T = np.array([[0.40, 0.20, 0.15, 0.10],[0.15, 0.40, 0.15, 0.20],[0.35,0.20, 0.50, 0.10],[0.10,0.20, 0.20, 0.60]])

# Exibição a matriz de transição
T

array([[0.4 , 0.2 , 0.15, 0.1 ],
       [0.15, 0.4 , 0.15, 0.2 ],
       [0.35, 0.2 , 0.5 , 0.1 ],
       [0.1 , 0.2 , 0.2 , 0.6 ]])

### Evolução do market share

Ao longo dos anos, à medida que os clientes mudam de operadora, as participações de mercado vão-se alterando.

In [4]:
# Evolução da participação de mercado ao londo de N anos

N = 3  # Número de anos à frente

for k in range(N):
    p.append(T @ p[k])   # Cada passo inclui um novo ano, usando a matriz de transição
    
# Exibição daa evolução do market share
print('Evolução do market share:')

Cabec = 'Ano     '
for x in Operadoras:
    Cabec += f'{x:8s}'
print(Cabec)

for k in range(N+1):
    Linha = f'{k:2}    '
    for j in range(len(Operadoras)):
        Linha += f'{p[k][j]:,.2%}  '
    print(Linha)

Evolução do market share:
Ano     A       B       C       D       
 0    40.00%  25.00%  20.00%  15.00%  
 1    25.50%  22.00%  30.50%  22.00%  
 2    21.38%  21.60%  30.77%  26.25%  
 3    20.11%  21.71%  29.81%  28.36%  


### Equilíbrio de mercado

A grande questão é: será que existe um equilíbrio de mercado? Ou seja, será que, ao longo do tempo as participações de mercado de cada operadora tendem a se estabilizar?

Note que, se houver um equilíbrio de mercado, ele corresponderá a um autovetor da matriz de transição, correspondente ao autovalor 1. Por isso, matematicamente, a busca de um equilíbrio de mercado corresponde à busca de autovetores do autovalor 1 da matriz.

In [5]:
# Cálculo de autovalores e autovetores
autovalores, autovetores = np.linalg.eig(T)

In [6]:
# Exibição da lista de autovalores
autovalores

array([1.        , 0.42071068, 0.2       , 0.27928932])

In [7]:
# Exibição da matriz de autovetores
# Cada coluna é um autovetor correspondente aos autovalores encontrados
autovetores

array([[-0.38333242,  0.13633675, -0.63245553, -0.26536301],
       [-0.43346051, -0.19280928,  0.31622777, -0.37527996],
       [-0.56025508,  0.7147646 ,  0.63245553,  0.86047689],
       [-0.5926909 , -0.65829207, -0.31622777, -0.21983391]])

In [8]:
if 1 in np.round(autovalores,8):   # Teste de existência de autovalor 1
    print('Equilíbrio de mercado:')
    # Seleção da posição do autovalor 1 na lista de autovalores
    AutoVal1pos = np.where(np.round(autovalores,8) == 1)[0][0]
    # Seleção da coluna da matriz de autovetores, correspondente ao autovalor 1
    AutoVet1 = autovetores[:,AutoVal1pos]     
    # Cálculo do ponto de equilíbrio
    Equilibrio = AutoVet1/AutoVet1.sum()
    # Exibição do equilíbrio de mercado
    for k in range(len(Operadoras)):
        print(f'- Operadora {Operadoras[k]}: {Equilibrio[k]:,.2%}')
        
else:
    print('Não existe equilíbrio de mercado.')

Equilíbrio de mercado:
- Operadora A: 19.46%
- Operadora B: 22.01%
- Operadora C: 28.44%
- Operadora D: 30.09%
